export const formatRupiah = (price: number) => {
    return new Intl.NumberFormat('id-ID', {
        style: 'currency',
        currency: 'IDR',
        minimumFractionDigits: 0,
    }).format(price);
};

export const categories = ["Semua", "Signature Box", "Nasi Kotak", "Paket Meeting", "Snack Box", "Tumpeng Mini"];
export const categoriesEn = ["All", "Signature Box", "Lunch Box", "Meeting Package", "Snack Box", "Mini Tumpeng"];

export const products = [
    {
        id: "1",
        name: "Nasi Box Ayam Bakar",
        nameEn: "Grilled Chicken Rice Box",
        description: "Nasi putih legit dengan ayam bakar bumbu rujak, lalapan segar, tahu tempe, dan sambal terasi khas Bu Anis.",
        descriptionEn: "Fragrant white rice served with grilled chicken in rujak spices, fresh raw vegetables, tofu, tempeh, and Bu Anis' signature shrimp paste chili.",
        basePrice: 35000,
        image: "/images/nasi-box-ayam-bakar.jpg",
        category: "Nasi Kotak",
        categoryEn: "Lunch Box",
    },
    {
        id: "2",
        name: "Nasi Langgi Komplit",
        nameEn: "Complete Langgi Rice",
        description: "Sajian premium dengan empal daging empuk, sambal goreng ati, serundeng, kering tempe, dan telur dadar iris.",
        descriptionEn: "Premium traditional dish with tender sweet beef (empal), liver spicy potato stew, toasted spiced coconut flakes (serundeng), caramelized tempeh, and sliced omelette.",
        basePrice: 45000,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800",
        category: "Signature Box",
        categoryEn: "Signature Box",
    },
    {
        id: "3",
        name: "Paket Meeting Hemat",
        nameEn: "Value Meeting Package",
        description: "Cocok untuk rapat kantor. Nasi uduk, ayam goreng laos, bihun goreng, kerupuk, dan air mineral.",
        descriptionEn: "Perfect for office meetings. Fragrant coconut rice (nasi uduk), galangal fried chicken, fried vermicelli, crackers, and mineral water.",
        basePrice: 30000,
        image: "https://images.unsplash.com/photo-1626804475297-41609ea1c2eb?auto=format&fit=crop&q=80&w=800",
        category: "Paket Meeting",
        categoryEn: "Meeting Package",
    },
    {
        id: "4",
        name: "Tumpeng Mini Kuning",
        nameEn: "Mini Yellow Tumpeng",
        description: "Tumpeng porsi personal yang cantik. Nasi kuning, perkedel, ayam suwir pedas, telur rawis, dan kering tempe.",
        descriptionEn: "Beautiful personal portion of traditional yellow rice cone, served with potato fritter (perkedel), spicy shredded chicken, sliced omelette, and caramelized tempeh.",
        basePrice: 40000,
        image: "https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&q=80&w=800",
        category: "Tumpeng Mini",
        categoryEn: "Mini Tumpeng",
    },
    {
        id: "5",
        name: "Snack Box Tradisional",
        nameEn: "Traditional Snack Box",
        description: "Kue lumpur, lemper ayam, risol mayo, dan air mineral gelas. Pas untuk pengajian atau coffee break.",
        descriptionEn: "Potato mud cake (kue lumpur), chicken sticky rice roll (lemper), risoles mayo, and a cup of mineral water. Perfect for gatherings or coffee breaks.",
        basePrice: 15000,
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=800",
        category: "Snack Box",
        categoryEn: "Snack Box",
    },
    {
        id: "6",
        name: "Nasi Box Rendang",
        nameEn: "Rendang Rice Box",
        description: "Rendang sapi empuk bumbu medok khas Padang, daun singkong rebus, sambal ijo, dan gulai nangka.",
        descriptionEn: "Tender beef rendang cooked in rich Padang spices, boiled cassava leaves, green chili paste, and jackfruit curry.",
        basePrice: 48000,
        image: "https://images.unsplash.com/photo-1627308595229-7830f5c90683?auto=format&fit=crop&q=80&w=800",
        category: "Nasi Kotak",
        categoryEn: "Lunch Box",
    }
];

export const translations = {
    id: {
        home: "Home",
        menuCatering: "Menu Catering",
        paketAcara: "Paket Acara",
        tanyaAdmin: "Tanya Admin",
        tanyaAdminWA: "Tanya Admin via WhatsApp",
        hubungiKami: "Hubungi Kami",
        jamOperasional: "Jam Operasional",
        hariBuka: "Senin - Sabtu: 07:00 - 17:00 WIB",
        hariLibur: "Minggu & Libur Nasional: Sesuai Pesanan",
        footerDesc: "Hadir menyajikan makanan otentik Nusantara untuk setiap momen berharga Anda. Bersih, halal, dan dimasak dengan cinta dari resep keluarga.",
        keranjang: "Keranjang",
        keranjangKosong: "Keranjang masih kosong nih.",
        subtotal: "Subtotal",
        checkoutWA: "Checkout via WhatsApp",
        catatanTambahan: "Catatan Tambahan (Opsional)",
        placeholderNotes: "Contoh: Pisah sambal, tambah kuah...",
        tambah: "Tambah",
        pesanYuk: "Pesan Yuk",
        qty: "Jumlah",
        catatan: "Catatan",
        harga: "Harga",
        totalPesanan: "Total Pesanan",
        msgInfoCheckout: "Mohon info ongkos kirim dan cara pembayarannya ya. Terima kasih!",
        tooltipWA: "💬 Tanya via WhatsApp",
        waMessageIntro: "Halo Nasi Catering Bu Anis, saya ingin bertanya tentang menu dan pemesanan catering. 😊",
        semua: "Semua"
    },
    en: {
        home: "Home",
        menuCatering: "Catering Menu",
        paketAcara: "Event Packages",
        tanyaAdmin: "Chat Admin",
        tanyaAdminWA: "Ask Admin via WhatsApp",
        hubungiKami: "Contact Us",
        jamOperasional: "Operating Hours",
        hariBuka: "Monday - Saturday: 07:00 - 17:00 WIB",
        hariLibur: "Sunday & National Holidays: By Order Only",
        footerDesc: "Proudly serving authentic Indonesian cuisine for your precious moments. Clean, halal, and cooked with love from family recipes.",
        keranjang: "Cart",
        keranjangKosong: "Your cart is empty.",
        subtotal: "Subtotal",
        checkoutWA: "Checkout via WhatsApp",
        catatanTambahan: "Additional Notes (Optional)",
        placeholderNotes: "Example: Separate chili, add more gravy...",
        tambah: "Add",
        pesanYuk: "Order Now",
        qty: "Quantity",
        catatan: "Notes",
        harga: "Price",
        totalPesanan: "Total Order",
        msgInfoCheckout: "Please let me know the shipping fee and payment details. Thank you!",
        tooltipWA: "💬 Ask via WhatsApp",
        waMessageIntro: "Hello Nasi Catering Bu Anis, I would like to ask about the catering menu and ordering. 😊",
        semua: "All"
    }
};